spring:
  application:
    name: voltradar-backend
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:voltradar}
    username: ${DB_USER:voltradar}
    password: ${DB_PASSWORD:voltradar_secret}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
        format_sql: true
    show-sql: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  threads:
    virtual:
      enabled: true

server:
  port: 8080

logging:
  level:
    sk.brutech.voltradar: DEBUG
    org.springframework.web: INFO
